/**
 * Generate the README's worked example — the numbers AND the figure — from the real
 * pricing path, so the picture cannot drift from the model.
 *
 * The previous figures were hand-drawn and outlived the lever they described: they were
 * still showing a routing saving after routing was retired for changing which model
 * answers. A generated figure fails loudly instead, because it is recomputed from
 * `simulate()` every time it is regenerated.
 *
 *   bun run bench/margin-model.ts            # print the table
 *   bun run bench/margin-model.ts --write    # also rewrite docs/img/savings-waterfall.svg
 */
import { computeMetrics } from "../src/metrics";
import { formatCents, microCentsToCents } from "../src/pricing";
import { RATE_CARD_2026_08_08 as CARD } from "../src/rates";
import { simulate } from "../src/simulate";
import type { UsageEvent } from "../src/types";

/** A heavy-Opus month with nothing cached — the worst case the lever can improve. */
const MONTH: UsageEvent[] = [{
  idempotencyKey: "worked-example", accountId: "example", projectId: "example",
  ts: "2026-08-01T00:00:00Z", sessionId: null, source: "claude_code", serviceTier: null, model: "claude-opus-5",
  inputTokens: 100_000_000, cacheReadTokens: 0, cacheCreationTokens: 0,
  cacheCreation5mTokens: 0, cacheCreation1hTokens: 0,
  outputTokens: 10_000_000,
  compactionInputTokens: 0, compactionOutputTokens: 0,
}];

const TARGET_CACHE_HIT_PCT = 90;
const WRITE_OVERHEAD_PCT = 5;

const metrics = computeMetrics(MONTH, CARD);
const sim = simulate(metrics, CARD, {
  targetCacheHitPct: TARGET_CACHE_HIT_PCT,
  cacheWriteOverheadPct: WRITE_OVERHEAD_PCT,
});

const baseline = sim.baselineMicroCents;
const saved = sim.attribution.cacheOnlySavedMicroCents;
const net = baseline - saved;
const pct = (saved / baseline) * 100;
const cents = (mc: number) => formatCents(microCentsToCents(mc));

console.log(`Worked example — 100 MTok input, 10 MTok output, all Opus 5, nothing cached.`);
console.log(`Cache target ${TARGET_CACHE_HIT_PCT}%, write overhead ${WRITE_OVERHEAD_PCT}%.\n`);
console.log(`| Line                                  | Cost      | Change     |`);
console.log(`|---------------------------------------|-----------|------------|`);
console.log(`| Baseline, uncached                    | ${cents(baseline).padEnd(9)} | —          |`);
console.log(`| Cache hit raised to ${TARGET_CACHE_HIT_PCT}%              | ${cents(net).padEnd(9)} | ${("−" + cents(saved)).padEnd(10)} |`);
console.log(`| **Net**                               | **${cents(net)}** | **${pct.toFixed(1)}% off** |`);
console.log(`\nWaste elimination: ${sim.attribution.wasteOnly} — no signal for it in slice 1.`);
console.log(`Routing: absent by design. A different model answering is a different answer.`);

if (process.argv.includes("--write")) {
  const W = 760, H = 240, PAD = 56, BAR = 62;
  const scale = (mc: number) => Math.round(((W - PAD * 2) * mc) / baseline);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}" font-family="ui-sans-serif,system-ui,sans-serif" role="img" aria-label="Waterfall: ${cents(baseline)} uncached baseline, minus ${cents(saved)} from raising cache hit to ${TARGET_CACHE_HIT_PCT}%, leaving ${cents(net)} — ${pct.toFixed(1)}% off">
  <rect width="${W}" height="${H}" fill="#ffffff"/>
  <text x="${PAD}" y="34" font-size="15" font-weight="600" fill="#0f1619">One lever, measured: cache</text>
  <text x="${PAD}" y="54" font-size="12" fill="#61747a">100 MTok in / 10 MTok out, all Opus 5, nothing cached to start</text>

  <rect x="${PAD}" y="76" width="${scale(baseline)}" height="${BAR / 2}" rx="3" fill="#d3dcde"/>
  <text x="${PAD + 8}" y="${76 + BAR / 4 + 5}" font-size="13" fill="#0f1619">Baseline, uncached</text>
  <text x="${PAD + scale(baseline) - 8}" y="${76 + BAR / 4 + 5}" font-size="13" text-anchor="end" fill="#0f1619" font-weight="600">${cents(baseline)}</text>

  <rect x="${PAD + scale(net)}" y="128" width="${scale(saved)}" height="${BAR / 2}" rx="3" fill="#1d6b48"/>
  <text x="${PAD + scale(net) - 8}" y="${128 + BAR / 4 + 5}" font-size="13" text-anchor="end" fill="#1d6b48" font-weight="600">−${cents(saved)}</text>
  <text x="${PAD + scale(net) + 10}" y="${128 + BAR / 4 + 5}" font-size="12" fill="#ffffff">cache hit → ${TARGET_CACHE_HIT_PCT}%</text>

  <rect x="${PAD}" y="180" width="${scale(net)}" height="${BAR / 2}" rx="3" fill="#0e6e86"/>
  <text x="${PAD + 8}" y="${180 + BAR / 4 + 5}" font-size="13" fill="#ffffff">Net</text>
  <text x="${PAD + scale(net) - 8}" y="${180 + BAR / 4 + 5}" font-size="13" text-anchor="end" fill="#ffffff" font-weight="600">${cents(net)}</text>

  <text x="${W - PAD}" y="${H - 12}" font-size="12" text-anchor="end" fill="#61747a">${pct.toFixed(1)}% off · generated by bench/margin-model.ts</text>
</svg>
`;
  await Bun.write(new URL("../docs/img/savings-waterfall.svg", import.meta.url).pathname, svg);
  console.log("\nwrote docs/img/savings-waterfall.svg");
}
